name: Metrics
on:
  schedule: [{cron: "0 15 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          debug: yes
          
          # ■ レイアウト設定
          template: classic
          config_timezone: Asia/Tokyo

          # ■ 基本情報 (Base)
          # "repositories" を削除し、"10 Repositories" や容量などのブロックを消しました
          base: header

          # ■ 自己紹介 (Introduction)
          # "About Me" を削除
          plugin_introduction: no

          # ■ 共同開発者・関係者 (People)
          plugin_people: yes
          plugin_people_types: following
          plugin_people_limit: 24
          plugin_people_size: 28

          # ■ ページスピード (PageSpeed)
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://github.com/0rnot
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}

          # ■ カレンダー (Calendar)
          plugin_calendar: yes
          plugin_calendar_limit: 1

          # ■ 使用言語 (Languages)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
