name: Metrics
on:
  # æ¯æ—¥ 0:00 (JST) ã«æ›´æ–°
  schedule: [{cron: "0 15 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: 0rnot
          token: ${{ secrets.METRICS_TOKEN }}

          # ğŸ’» ãƒãƒƒã‚«ãƒ¼ä»•æ§˜ã®ã‚¿ãƒ¼ãƒŸãƒŠãƒ«ãƒ»ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆ
          template: terminal
          
          # è¡¨ç¤ºã™ã‚‹é …ç›®ï¼ˆå…¨éƒ¨ç››ã‚Šï¼‰
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tokyo
          
          # æ‹¡å¼µãƒ—ãƒ©ã‚°ã‚¤ãƒ³
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_lines: yes
