name: Metrics
on:
  # 毎日 0:00 (JST) に更新
  schedule: [{cron: "0 15 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: 0rnot
          template: classic
          base: header, activity, community, repositories, metadata
          token: ${{ secrets.METRICS_TOKEN }}

          # 【ここが魔法の1行】
          # これを入れると、文字リストが「レーダーチャート」に進化します
          config_display: large

          # 画像左側の「Contributed to...」を出す設定
          plugin_introduction: yes
          plugin_introduction_title: yes

          # 右側の詳細データ
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
